FROM python:3.13-slim

RUN apt-get update && apt-get install

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml ./
COPY uv.lock ./

RUN uv sync

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app

COPY config/ /app/config/
COPY prisma_db/ /app/prisma_db/
COPY src_api/ /app/src_api/

COPY chat/ /app/chat/


EXPOSE 8008

CMD ["uv", "run", "uvicorn", "chat.main:app", "--host", "0.0.0.0", "--port", "8008"]

