services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  
  ml:
    build:
      context: .
      dockerfile: ./src_ml/Dockerfile.ml
    container_name: ml
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    
  db:
    image: ankane/pgvector:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  worker:
    build: 
      context: .
      dockerfile: workers/Dockerfile.worker
    container_name: worker
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  scheduler:
    build: 
      context: .
      dockerfile: workers/Dockerfile.worker
    container_name: scheduler
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: ["taskiq", "scheduler", "workers.app:scheduler"]
  
  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile.chat
    container_name: chat
    ports:
      - "8008:8008"
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET_KEY}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  pgdata:
  redisdata: