FROM python:3.13-slim

RUN pip install --no-cache-dir uv

WORKDIR /worker

COPY workers/pyproject.toml ./pyproject.toml
COPY workers/uv.lock ./uv.lock

RUN uv sync 

ENV PATH="/app/.venv/bin:$PATH"

COPY . .

EXPOSE 8000

CMD ["uv", "run", "taskiq", "worker", "workers.app:broker", "workers.tasks"]
