FROM python:3.13-slim

RUN pip install --no-cache-dir uv

WORKDIR /worker

COPY pyproject.toml ./
COPY uv.lock ./

RUN uv sync 

ENV PATH="/app/.venv/bin:$PATH"

COPY . .

EXPOSE 8000

CMD ["uv", "run", "taskiq", "worker", "worker.app:broker", "reload"]
